### ISSUE TITLE
`-ms` vendor prefix should not be capitalized in react mode

### ISSUE THREAD

**Issue by frankdannhauer** [remarkablemark/style-to-js#2]
## Expected Behavior
When reactCompat set to `true` the `-ms`  vendor prefix should _not_ be capitalized. See 
* https://github.com/facebook/react/blob/8197c73ec334e4430d892cead14aa371f13467a9/packages/react-dom/src/shared/warnValidStyle.js#L11
* https://github.com/frenic/csstype/blob/b1318fd65bc177ef7546fdd087aba9ab449a021d/index.js.flow#L2229

## Actual Behavior

`-ms-transform` becomes `MsTransform` instead of `msTransform`

**Comment by remarkablemark** [comment]
Thanks for opening this issue @frankdannhauer! Would you be interested in opening a PR?

**Comment by remarkablemark** [comment]
Release https://github.com/remarkablemark/style-to-js/pull/4#issuecomment-1141455883
