### ISSUE TITLE
The CSS Custom Property Regex Does Not Allow Underscores

### ISSUE THREAD

**Issue by joshualip-plaudit** [remarkablemark/style-to-js#502]
## Expected Behavior

`"--test_ing: 33"` should be converted to `{"--test_ing": "33"}`

## Actual Behavior

`"--test_ing: 33"` is converted to `{"-Test_ing": "33"}`

## Steps to Reproduce

Create a JS file with the following contents and run it:
```javascript
const styleToObj = require("style-to-js");
console.log(styleToObj("--testing: 33; --test_ing: 33"));
```

The output will be:
```javascript
{ '--testing': '33', '-Test_ing': '33' }
```

## Reproducible Demo
JSFiddle: https://jsfiddle.net/2pbnvoa6/

## Environment

- Version: 1.1.15

## Fix

This behavior is caused by an error in the CUSTOM_PROPERTY_REGEX constant. It is:
```javascript
const CUSTOM_PROPERTY_REGEX = /^--[a-zA-Z0-9-]+$/;
```
It should be:
```javascript
const CUSTOM_PROPERTY_REGEX = /^--[a-zA-Z0-9_-]+$/;
```

**Comment by remarkablemark** [comment]
@joshualip-plaudit would you like to open a PR?

**Comment by joshualip-plaudit** [comment]
I don't have the project checked out, so it'd probably be faster for you to make the update?

I can get started on one, though.
